wandb_version: 1

batch_size:
  value: 15
learning_rate:
  value: 0.00032198084145240935
omega_0:
  value: 57
shared_depth:
  value: 8
shared_width:
  value: 320
unique_depth:
  value: 2
unique_width:
  value: 128
