wandb_version: 1

batch_size:
  value: 25
learning_rate:
  value: 9.547814859238038e-05
omega_0:
  value: 30
shared_depth:
  value: 6
shared_width:
  value: 256
unique_depth:
  value: 2
unique_width:
  value: 128
