wandb_version: 1

batch_size:
  value: 75
learning_rate:
  value: 3.1865516887557035e-05
omega_0:
  value: 51
shared_depth:
  value: 12
shared_width:
  value: 256
unique_depth:
  value: 2
unique_width:
  value: 128
