wandb_version: 1

batch_size:
  value: 10
learning_rate:
  value: 0.0004229912036510938
omega_0:
  value: 24
shared_depth:
  value: 7
shared_width:
  value: 128
unique_depth:
  value: 2
unique_width:
  value: 160
