wandb_version: 1

batch_size:
  value: 5
learning_rate:
  value: 0.00023027798566862455
omega_0:
  value: 42
shared_depth:
  value: 6
shared_width:
  value: 128
unique_depth:
  value: 2
unique_width:
  value: 96
