wandb_version: 1

batch_size:
  value: 0
learning_rate:
  value: 0.0006980119531288905
omega_0:
  value: 24
shared_depth:
  value: 7
shared_width:
  value: 256
unique_depth:
  value: 1
unique_width:
  value: 128
