wandb_version: 1

epochs:
  desc: null
  value: 100000
patience:
  desc: null
  value: 100
learning_rate:
  desc: null
  value: 0.0004229912036510938
batch_size:
  desc: null
  value: 10
shared_width:
  desc: null
  value: 128
shared_depth:
  desc: null
  value: 7
unique_width:
  desc: null
  value: 160
unique_depth:
  desc: null
  value: 2
omega_0:
  desc: null
  value: 24
_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.18.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1729754069
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      - 37
      4: 3.11.3
      5: 0.18.5
      8:
      - 5
      13: linux-x86_64
