wandb_version: 1

batch_size:
  value: 35
learning_rate:
  value: 0.0001571029981031835
omega_0:
  value: 21
shared_depth:
  value: 9
shared_width:
  value: 256
unique_depth:
  value: 1
unique_width:
  value: 128
