wandb_version: 1

batch_size:
  value: 80
learning_rate:
  value: 1.7299704201520872e-05
omega_0:
  value: 48
shared_depth:
  value: 7
shared_width:
  value: 256
unique_depth:
  value: 1
unique_width:
  value: 64
