wandb_version: 1

batch_size:
  value: 65
learning_rate:
  value: 0.0003848964575598498
omega_0:
  value: 18
shared_depth:
  value: 7
shared_width:
  value: 384
unique_depth:
  value: 3
unique_width:
  value: 96
