wandb_version: 1

pretrained model:
  desc: null
  value: false
meta_learning_rate:
  desc: null
  value: 0.001
inner_learning_rate:
  desc: null
  value: 0.001
max_epochs:
  desc: null
  value: 4000
meta-patience:
  desc: null
  value: 10
K:
  desc: null
  value: 10
batch_size:
  desc: null
  value: 5
omega_0:
  desc: null
  value: 30
Inner loss function:
  desc: null
  value: MSE
Outer loss function:
  desc: null
  value: MSE
_wandb:
  desc: null
  value:
    python_version: 3.11.10
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1729535806.0
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.11.10
      5: 0.16.6
      8:
      - 3
      - 5
      13: windows-amd64
