_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.3
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.11.3
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size:
    value: 5
epochs:
    value: 100000
learning_rate:
    value: 0.0006
omega_0:
    value: 30
patience:
    value: 50
shared_depth:
    value: 7
shared_width:
    value: 320
unique_depth:
    value: 1
unique_width:
    value: 160
